### ISSUE TITLE
the demo doesn't work

### ISSUE THREAD

**Issue by nginm** [adithyaanil1999/manga-reader-express#1]
I have no access to the demo site, can you provide some alternative pictures. Better if you have a video tutorial on your source code - I'm a non-programming person. Thank you .

**Comment by adithyaanil1999** [comment]
It does work, its a REST api I made to scrape manga info from mangakakalot. You need to send a POST request to the url routes, the actual front end where you can read manga is still being constructed [here](https://github.com/adithyaanil1999/manga-reader-ang).
