### ISSUE TITLE
How do we well... use it?

### ISSUE THREAD

**Issue by wynwxst** [adithyaanil1999/manga-reader-express#3]

**Comment by adithyaanil1999** [comment]
The endpoints are defined in https://github.com/adithyaanil1999/manga-reader-express/blob/master/routes/scraper/scraper.js
Currently only mangaJar and Readcomicsonline works.

I will add more sources soon.

**Comment by wynwxst** [comment]
maybe mangareader.to? yeah I saw the endpoints and tested them with requests

**Comment by adithyaanil1999** [comment]
yea looks good, ill add this website, currently working on a new front-end. current PWA app is too limiting, the whole point of this project was because of lack of good manga apps like tachiyomi on iOS. Just give me some time

**Comment by wynwxst** [comment]
> yea looks good, ill add this website, currently working on a new front-end. current PWA app is too limiting, the whole point of this project was because of lack of good manga apps like tachiyomi on iOS. Just give me some time

that's true i was thinking of making a similar wrapper anyways

**Comment by adithyaanil1999** [comment]
good luck, the main issue is most of these websites are protected by cloudfare which means you'll just get 1020 error when trying to access the content so make sure the website you are scrapping from doesnt have that

**Comment by wynwxst** [comment]
@adithyaanil1999 
```python
import cloudscraper

scraper = cloudscraper.create_scraper()  # returns a CloudScraper instance
# Or: scraper = cloudscraper.CloudScraper()  # CloudScraper inherits from requests.Session
print scraper.get("http://somesite.com").text  
```
It bypasses cloudflare, you can also use `cfscrape`

**Comment by adithyaanil1999** [comment]
You cant use this in the front-end AFAIK
